services:
  - type: web
    name: autumn-chat
    env: docker
    dockerfilePath: Dockerfile
    instanceCount: 1
    envVars:
      - key: SECRET_KEY
        value: replace-with-your-secret
      - key: PORT
        value: '5000'
databases:
  - name: autumn-db
    envVar: DATABASE_URL
